name: Continuous Delivery Pipeline

on:
  push:
    branches: [ main ]

jobs:
  # ==========================================
  # STAGE 1: DEPLOY TO STAGING (Runs First)
  # ==========================================
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Apply (Staging)
        run: |
          cd infra/environments/staging
          terraform init
          terraform apply -auto-approve
          echo "STAGING_EC2_IP=$(terraform output -raw staging_ec2_ip)" >> $GITHUB_ENV
          echo "STAGING_CF_ID=$(terraform output -raw staging_cloudfront_id)" >> $GITHUB_ENV

      - name: Build & Deploy Frontend to Staging S3
        run: |
          cd frontend
          npm install && npm run build
          aws s3 sync dist/ s3://kashan-my-app-frontend-staging --delete
          aws cloudfront create-invalidation --distribution-id ${{ env.STAGING_CF_ID }} --paths "/*"

      - name: Deploy Backend to Staging EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.STAGING_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.KEYFOREC2 }}
          script: |
            set -e
            if [ ! -d "$HOME/app" ]; then
              git clone https://github.com/${{ github.repository }}.git $HOME/app
            fi
            cd $HOME/app
            git fetch --all && git checkout main && git pull origin main
            echo "IMAGE_TAG=sha-${{ github.sha }}" > .env
            echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}" >> .env
            echo "GRAFANA_ADMIN_USER=admin" >> .env
            echo "GRAFANA_ADMIN_PASSWORD=admin" >> .env
            sudo docker compose up -d --build

  # ==========================================
  # STAGE 2: MANUAL APPROVAL & DEPLOY TO PROD
  # ==========================================
  deploy-production:
    name: Deploy to Production
    needs: deploy-staging          # Waits for Staging to complete first
    environment: prod        # Pauses pipeline here for approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Apply (Production)
        run: |
          cd infra/environments/prod
          terraform init
          terraform apply -auto-approve
          echo "PROD_EC2_IP=$(terraform output -raw prod_ec2_ip)" >> $GITHUB_ENV
          echo "PROD_CF_ID=$(terraform output -raw prod_cloudfront_id)" >> $GITHUB_ENV

      - name: Build & Deploy Frontend to Prod S3
        run: |
          cd frontend
          npm install && npm run build
          aws s3 sync dist/ s3://kashan-my-app-frontend-prod --delete
          aws cloudfront create-invalidation --distribution-id ${{ env.PROD_CF_ID }} --paths "/*"

      - name: Deploy Backend to Prod EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.PROD_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.KEYFOREC2 }}
          script: |
            set -e
            if [ ! -d "$HOME/app" ]; then
              git clone https://github.com/${{ github.repository }}.git $HOME/app
            fi
            cd $HOME/app
            git fetch --all && git checkout main && git pull origin main
            echo "IMAGE_TAG=sha-${{ github.sha }}" > .env
            echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}" >> .env
            echo "GRAFANA_ADMIN_USER=admin" >> .env
            echo "GRAFANA_ADMIN_PASSWORD=admin" >> .env
            sudo docker compose up -d --build
